;/* This is auto-generated ASM code from LDmicro. Do not edit this file!
;   Go back to the LDmicro ladder diagram source for changes in the ladder logic. */
;Atmel AVR ATmega328 28-PDIP is the LDmicro target processor.
.DEVICE ATmega328
;#pragma AVRPART ADMIN PART_NAME ATmega328
;.INCLUDE <m328def.inc>
.CSEG
.ORG 0x0
;TABSIZE = 8
    ; Set up I/O pins
    ; GOTO progStart
    ; WriteRuntime
          ldi 	 r30, 	 0x25	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
          reti 	 		 ; (OP_RETI)
    ; Interrupt table end.
    ; This is Reset Vector
    ; ConfigureTimerForPlcCycle
l_000025: ldi 	 r30, 	 0x80	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_TCCR1A, 0x00)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, val, lit) ; val=0 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x81	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_TCCR1B, ((1 << WGM12) | plcTmr.cs) & 0xff)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0xC	 ; (OP_LDI, r25, val, lit) ; val=12 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x89	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_OCR1AH, BYTE((counter >> 8) & 0xff))
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x2	 ; (OP_LDI, r25, val, lit) ; val=2 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x88	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_OCR1AL, BYTE(counter & 0xff))
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x70	 ; (OP_LDI, r25, val, lit) ; val=112 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
    ; Watchdog on
          cli 	 		 ; (OP_CLI)
          wdr 	 		 ; (OP_WDR)
          ldi 	 r25, 	 0x18	 ; (OP_LDI, r25, val)
          ldi 	 r30, 	 0x60	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; - Got only four cycles to set the new values from here! -
          ldi 	 r25, 	 0x29	 ; (OP_LDI, r25, val)
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25)
          sei 	 		 ; (OP_SEI)
    ; Set up the stack, which we use only when we jump to multiply/divide routine
          ldi 	 r30, 	 0x5E	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_SPH, topOfMemory >> 8, topOfMemory)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x8	 ; (OP_LDI, r25, val, lit) ; val=8 lit=0x8FF=2303
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x5D	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (REG_SPL, topOfMemory & 0xff, topOfMemory)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0xFF	 ; (OP_LDI, r25, val, lit) ; val=255 lit=0x8FF=2303
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
    ; Zero out the memory used for timers, internal relays, etc.
          ldi 	 r26, 	 0x0	 ; (OP_LDI, XL, (addr & 0xff), comment)
          ldi 	 r27, 	 0x9	 ; (OP_LDI, XH, (addr >> 8))
          ldi 	 r16, 	 0x0	 ; (OP_LDI, 16, 0)
          ldi 	 r24, 	 0x0	 ; (OP_LDI, r24, (Prog.mcu()->ram[0].len) & 0xff)
          ldi 	 r25, 	 0x8	 ; (OP_LDI, r25, (Prog.mcu()->ram[0].len) >> 8)
l_00004b: st  	 -X, 	 r16	 ; (OP_ST_XS, 16)
          sbiw 	 r25:r24, 1	 ; (OP_SBIW, r24, 1)
          brne 	 l_00004b 	 ; (OP_BRNE, loopZero)
    ; Set up I/O pins
    ; Turn on the pull-ups, and drive the outputs low to start
          ldi 	 r30, 	 0x24	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->dirRegs[i], isOutput[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x7	 ; (OP_LDI, r25, val, lit) ; val=7 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x25	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->outputRegs[i], isInput[i] & Prog.pullUpRegs[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, val, lit) ; val=0 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x27	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->dirRegs[i], isOutput[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, val, lit) ; val=0 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x28	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->outputRegs[i], isInput[i] & Prog.pullUpRegs[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, val, lit) ; val=0 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x2A	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->dirRegs[i], isOutput[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0xC0	 ; (OP_LDI, r25, val, lit) ; val=192 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
          ldi 	 r30, 	 0x2B	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; (Prog.mcu()->outputRegs[i], isInput[i] & Prog.pullUpRegs[i])
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x8	 ; (OP_LDI, r25, val, lit) ; val=8 lit=0x0=0
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25, 0, name)
    ; Begin Of PLC Cycle
l_000066: ldi 	 r30, 	 0x36	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
l_000068: ld  	 r25, 	 Z	 ; (OP_LD_Z, reg)
          sbrs 	 r25, 	 1	 ; (OP_SBRS, reg, bit)
          rjmp 	 l_000068 	 ; (OP_RJMP, AvrProg.size() - std::min(skbs, uint32_t(2)))
          ldi 	 r30, 	 0x36	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name)
          sbr 	 r25, 	 0x2	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; Watchdog reset
          wdr 	 		 ; (OP_WDR)
    ; CompileFromIntermediate BEGIN
    ; INIT TABLES
    ; 
    ; ======= START RUNG 1 =======
    ; INT_AllocKnownAddr Rung1
    ; INT_SET_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR Xpulsador
          ldi 	 r30, 	 0x29	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; Xpulsador
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_000080 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_COIL
    ; INT_IF_BIT_SET $rung_top
l_000080: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_00008a 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R1
          sbr 	 r25, 	 0x2	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish series
    ; 
    ; ======= START RUNG 2 =======
    ; INT_AllocKnownAddr Rung2
    ; INT_SET_BIT $rung_top
l_00008a: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R1
          sbrc 	 r25, 	 1	 ; (OP_SBRC, r25, bit, b) ; BIT1
          rjmp 	 l_000099 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T1 1000000
    ; INT_IF_BIT_SET $rung_top
l_000099: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_0000b1 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x1	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T1
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_0000ae 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T1
          ldi 	 r30, 	 0x1	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_0000ae: ldi 	 r30, 	 0xB5	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T1:=0x0(0)
l_0000b1: ldi 	 r30, 	 0x1	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T1
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_0:=$rung_top
l_0000b5: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 2	 ; (OP_BLD, r25, bitDest, d) ; BIT2
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_0
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_0
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_0
          sbrs 	 r25, 	 2	 ; (OP_SBRS, reg, bit, b) ; BIT2
          rjmp 	 l_0000c5 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R2
          sbr 	 r25, 	 0x8	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_0:=$rung_top
l_0000c5: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 2	 ; (OP_BLD, r25, bitDest, d) ; BIT2
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_0
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_0
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_0
          sbrs 	 r25, 	 2	 ; (OP_SBRS, reg, bit, b) ; BIT2
          rjmp 	 l_0000d5 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R1
          cbr 	 r25, 	 0x2	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 3 =======
    ; INT_AllocKnownAddr Rung3
    ; INT_SET_BIT $rung_top
l_0000d5: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R2
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_0000e4 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR Xpulsador
l_0000e4: ldi 	 r30, 	 0x29	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; Xpulsador
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_0000ee 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_1:=$rung_top
l_0000ee: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 4	 ; (OP_BLD, r25, bitDest, d) ; BIT4
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_1
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_1
          sbrs 	 r25, 	 4	 ; (OP_SBRS, reg, bit, b) ; BIT4
          rjmp 	 l_0000fe 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R3
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R3
          sbr 	 r25, 	 0x20	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_1:=$rung_top
l_0000fe: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 4	 ; (OP_BLD, r25, bitDest, d) ; BIT4
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_1
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_1
          sbrs 	 r25, 	 4	 ; (OP_SBRS, reg, bit, b) ; BIT4
          rjmp 	 l_00010e 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R2
          cbr 	 r25, 	 0x8	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 4 =======
    ; INT_AllocKnownAddr Rung4
    ; INT_SET_BIT $rung_top
l_00010e: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R3
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R3
          sbrc 	 r25, 	 5	 ; (OP_SBRC, r25, bit, b) ; BIT5
          rjmp 	 l_00011d 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T2 1000000
    ; INT_IF_BIT_SET $rung_top
l_00011d: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_000135 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x2	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T2
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_000132 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T2
          ldi 	 r30, 	 0x2	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_000132: ldi 	 r30, 	 0x39	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T2:=0x0(0)
l_000135: ldi 	 r30, 	 0x2	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T2
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_2:=$rung_top
l_000139: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 6	 ; (OP_BLD, r25, bitDest, d) ; BIT6
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_2
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_2
          sbrs 	 r25, 	 6	 ; (OP_SBRS, reg, bit, b) ; BIT6
          rjmp 	 l_000149 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R4
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R4
          sbr 	 r25, 	 0x80	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_2:=$rung_top
l_000149: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          bld 	 r25, 	 6	 ; (OP_BLD, r25, bitDest, d) ; BIT6
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_2
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_2
          sbrs 	 r25, 	 6	 ; (OP_SBRS, reg, bit, b) ; BIT6
          rjmp 	 l_000159 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R3
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R3
          cbr 	 r25, 	 0x20	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 5 =======
    ; INT_AllocKnownAddr Rung5
    ; INT_SET_BIT $rung_top
l_000159: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R4
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R4
          sbrc 	 r25, 	 7	 ; (OP_SBRC, r25, bit, b) ; BIT7
          rjmp 	 l_000168 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T3 1000000
    ; INT_IF_BIT_SET $rung_top
l_000168: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_000180 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x3	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T3
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_00017d 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T3
          ldi 	 r30, 	 0x3	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_00017d: ldi 	 r30, 	 0x84	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T3:=0x0(0)
l_000180: ldi 	 r30, 	 0x3	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T3
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_3:=$rung_top
l_000184: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 0	 ; (OP_BLD, r25, bitDest, d) ; BIT0
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_3
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_3
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_3
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_000197 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R5
          sbr 	 r25, 	 0x2	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_3:=$rung_top
l_000197: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 0	 ; (OP_BLD, r25, bitDest, d) ; BIT0
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_3
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_3
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_3
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_0001aa 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R4
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R4
          cbr 	 r25, 	 0x80	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 6 =======
    ; INT_AllocKnownAddr Rung6
    ; INT_SET_BIT $rung_top
l_0001aa: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R5
          sbrc 	 r25, 	 1	 ; (OP_SBRC, r25, bit, b) ; BIT1
          rjmp 	 l_0001b9 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR Xpulsador
l_0001b9: ldi 	 r30, 	 0x29	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; Xpulsador
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_0001c3 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_4:=$rung_top
l_0001c3: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 2	 ; (OP_BLD, r25, bitDest, d) ; BIT2
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_4
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_4
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_4
          sbrs 	 r25, 	 2	 ; (OP_SBRS, reg, bit, b) ; BIT2
          rjmp 	 l_0001d6 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R6
          sbr 	 r25, 	 0x8	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_4:=$rung_top
l_0001d6: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 2	 ; (OP_BLD, r25, bitDest, d) ; BIT2
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_4
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_4
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_4
          sbrs 	 r25, 	 2	 ; (OP_SBRS, reg, bit, b) ; BIT2
          rjmp 	 l_0001e9 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R5
          cbr 	 r25, 	 0x2	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 7 =======
    ; INT_AllocKnownAddr Rung7
    ; INT_SET_BIT $rung_top
l_0001e9: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R6
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_0001f8 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T4 1000000
    ; INT_IF_BIT_SET $rung_top
l_0001f8: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_000210 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x5	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T4
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_00020d 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T4
          ldi 	 r30, 	 0x5	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_00020d: ldi 	 r30, 	 0x14	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x2	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T4:=0x0(0)
l_000210: ldi 	 r30, 	 0x5	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T4
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_5:=$rung_top
l_000214: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 4	 ; (OP_BLD, r25, bitDest, d) ; BIT4
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_5
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_5
          sbrs 	 r25, 	 4	 ; (OP_SBRS, reg, bit, b) ; BIT4
          rjmp 	 l_000227 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R7
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R7
          sbr 	 r25, 	 0x20	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_5:=$rung_top
l_000227: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 4	 ; (OP_BLD, r25, bitDest, d) ; BIT4
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_5
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_5
          sbrs 	 r25, 	 4	 ; (OP_SBRS, reg, bit, b) ; BIT4
          rjmp 	 l_00023a 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R6
          cbr 	 r25, 	 0x8	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 8 =======
    ; INT_AllocKnownAddr Rung8
    ; INT_SET_BIT $rung_top
l_00023a: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R7
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R7
          sbrc 	 r25, 	 5	 ; (OP_SBRC, r25, bit, b) ; BIT5
          rjmp 	 l_000249 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T5 1000000
    ; INT_IF_BIT_SET $rung_top
l_000249: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_000261 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x6	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T5
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_00025e 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T5
          ldi 	 r30, 	 0x6	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_00025e: ldi 	 r30, 	 0x65	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x2	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T5:=0x0(0)
l_000261: ldi 	 r30, 	 0x6	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T5
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; start parallel [
    ; INT_COPY_BIT_TO_BIT $parThis_6:=$rung_top
l_000265: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 6	 ; (OP_BLD, r25, bitDest, d) ; BIT6
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_6
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_6
          sbrs 	 r25, 	 6	 ; (OP_SBRS, reg, bit, b) ; BIT6
          rjmp 	 l_000278 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT R8
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R8
          sbr 	 r25, 	 0x80	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_6:=$rung_top
l_000278: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 6	 ; (OP_BLD, r25, bitDest, d) ; BIT6
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_6
    ; ELEM_COIL
    ; INT_IF_BIT_SET $parThis_6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_6
          sbrs 	 r25, 	 6	 ; (OP_SBRS, reg, bit, b) ; BIT6
          rjmp 	 l_00028b 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R7
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R7
          cbr 	 r25, 	 0x20	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish parallel
    ; ] finish series
    ; 
    ; ======= START RUNG 9 =======
    ; INT_AllocKnownAddr Rung9
    ; INT_SET_BIT $rung_top
l_00028b: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R8
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R8
          sbrc 	 r25, 	 7	 ; (OP_SBRC, r25, bit, b) ; BIT7
          rjmp 	 l_00029a 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_TON T6 1000000
    ; INT_IF_BIT_SET $rung_top
l_00029a: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_0002b2 	 ; (OP_RJMP, condFalse)
    ; INT_IF_LES
          ldi 	 r26, 	 0x7	 ; (OP_LDI, XL, (addr & 0xff), comment) ; T6
          ldi 	 r27, 	 0x1	 ; (OP_LDI, XH, (addr >> 8))
          ld  	 r20, 	 X+	 ; (op, reg + i)
          ldi 	 r16, 	 0x64	 ; (OP_LDI, reg, literal & 0xff, comment)
          cp  	 r20, 	 r16	 ; (OP_CP, 20, 16)
          brge 	 l_0002af 	 ; (OP_BRGE, notTrue, 0)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_INCREMENT_VARIABLE T6
          ldi 	 r30, 	 0x7	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          inc 	 r25 		 ; (OP_INC, r25, 0, name)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
l_0002af: ldi 	 r30, 	 0xB6	 ; (OP_LDI, ZL, FWD_LO(addr))
          ldi 	 r31, 	 0x2	 ; (OP_LDI, ZH, FWD_HI(addr))
          ijmp 	 		 ; (OP_IJMP, FWD(addr))
    ; INT_SET_VARIABLE_TO_LITERAL T6:=0x0(0)
l_0002b2: ldi 	 r30, 	 0x7	 ; (OP_LDI, ZL, (addr & 0xff), comment) ; T6
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ldi 	 r25, 	 0x0	 ; (OP_LDI, r25, lNow)
          st  	 Z+, 	 r25	 ; (OP_ST_ZP, r25)
    ; ELEM_COIL
    ; INT_IF_BIT_SET $rung_top
l_0002b6: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbrs 	 r25, 	 0	 ; (OP_SBRS, reg, bit, b) ; BIT0
          rjmp 	 l_0002c0 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT R8
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; R8
          cbr 	 r25, 	 0x80	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ] finish series
    ; 
    ; ======= START RUNG 10 =======
    ; INT_AllocKnownAddr Rung10
    ; Activaci¢n de salidas
    ; 
    ; ======= START RUNG 11 =======
    ; INT_AllocKnownAddr Rung11
    ; INT_SET_BIT $rung_top
l_0002c0: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R8
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R8
          sbrc 	 r25, 	 7	 ; (OP_SBRC, r25, bit, b) ; BIT7
          rjmp 	 l_0002cf 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_COIL
    ; INT_COPY_BIT_TO_BIT YON_OFF:=$rung_top
l_0002cf: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x25	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 2	 ; (OP_BLD, r25, bitDest, d) ; BIT2
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; YON_OFF
    ; ] finish series
    ; 
    ; ======= START RUNG 12 =======
    ; INT_AllocKnownAddr Rung12
    ; INT_SET_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; start parallel [
    ; INT_CLEAR_BIT $parOut_0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_0
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_7:=$rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 1	 ; (OP_BLD, r25, bitDest, d) ; BIT1
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_7
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R1
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R1
          sbrc 	 r25, 	 1	 ; (OP_SBRC, r25, bit, b) ; BIT1
          rjmp 	 l_0002f5 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_7
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          cbr 	 r25, 	 0x2	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_7
l_0002f5: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          sbrs 	 r25, 	 1	 ; (OP_SBRS, reg, bit, b) ; BIT1
          rjmp 	 l_0002ff 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_0
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_7:=$rung_top
l_0002ff: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 1	 ; (OP_BLD, r25, bitDest, d) ; BIT1
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_7
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R3
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R3
          sbrc 	 r25, 	 5	 ; (OP_SBRC, r25, bit, b) ; BIT5
          rjmp 	 l_000312 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_7
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          cbr 	 r25, 	 0x2	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_7
l_000312: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          sbrs 	 r25, 	 1	 ; (OP_SBRS, reg, bit, b) ; BIT1
          rjmp 	 l_00031c 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_0
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_7:=$rung_top
l_00031c: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 1	 ; (OP_BLD, r25, bitDest, d) ; BIT1
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_7
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R6
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R6
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_00032f 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_7
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          cbr 	 r25, 	 0x2	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_7
l_00032f: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_7
          sbrs 	 r25, 	 1	 ; (OP_SBRS, reg, bit, b) ; BIT1
          rjmp 	 l_000339 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_0
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $rung_top:=$parOut_0
l_000339: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $parOut_0
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 0	 ; (OP_BLD, r25, bitDest, d) ; BIT0
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $rung_top
    ; ] finish parallel
    ; ELEM_COIL
    ; INT_COPY_BIT_TO_BIT YAlarma:=$rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x25	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 1	 ; (OP_BLD, r25, bitDest, d) ; BIT1
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; YAlarma
    ; ] finish series
    ; 
    ; ======= START RUNG 13 =======
    ; INT_AllocKnownAddr Rung13
    ; INT_SET_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; start parallel [
    ; INT_CLEAR_BIT $parOut_1
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_1
          cbr 	 r25, 	 0x4	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_8:=$rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 3	 ; (OP_BLD, r25, bitDest, d) ; BIT3
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_8
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R2
          sbrc 	 r25, 	 3	 ; (OP_SBRC, r25, bit, b) ; BIT3
          rjmp 	 l_000368 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_8
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          cbr 	 r25, 	 0x8	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_8
l_000368: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          sbrs 	 r25, 	 3	 ; (OP_SBRS, reg, bit, b) ; BIT3
          rjmp 	 l_000372 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_1
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_1
          sbr 	 r25, 	 0x4	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_8:=$rung_top
l_000372: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 3	 ; (OP_BLD, r25, bitDest, d) ; BIT3
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_8
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R4
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R4
          sbrc 	 r25, 	 7	 ; (OP_SBRC, r25, bit, b) ; BIT7
          rjmp 	 l_000385 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_8
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          cbr 	 r25, 	 0x8	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_8
l_000385: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          sbrs 	 r25, 	 3	 ; (OP_SBRS, reg, bit, b) ; BIT3
          rjmp 	 l_00038f 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_1
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_1
          sbr 	 r25, 	 0x4	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $parThis_8:=$rung_top
l_00038f: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 3	 ; (OP_BLD, r25, bitDest, d) ; BIT3
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $parThis_8
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R5
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R5
          sbrc 	 r25, 	 1	 ; (OP_SBRC, r25, bit, b) ; BIT1
          rjmp 	 l_0003a2 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $parThis_8
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          cbr 	 r25, 	 0x8	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_IF_BIT_SET $parThis_8
l_0003a2: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parThis_8
          sbrs 	 r25, 	 3	 ; (OP_SBRS, reg, bit, b) ; BIT3
          rjmp 	 l_0003ac 	 ; (OP_RJMP, condFalse)
    ; INT_SET_BIT $parOut_1
          ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $parOut_1
          sbr 	 r25, 	 0x4	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; INT_COPY_BIT_TO_BIT $rung_top:=$parOut_1
l_0003ac: ldi 	 r30, 	 0x8	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $parOut_1
          bst 	 r25, 	 2	 ; (OP_BST, r25, bitSrc, s) ; BIT2
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 0	 ; (OP_BLD, r25, bitDest, d) ; BIT0
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; $rung_top
    ; ] finish parallel
    ; ELEM_COIL
    ; INT_COPY_BIT_TO_BIT YTiempo:=$rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x25	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 0	 ; (OP_BLD, r25, bitDest, d) ; BIT0
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; YTiempo
    ; ] finish series
    ; 
    ; ======= START RUNG 14 =======
    ; INT_AllocKnownAddr Rung14
    ; INT_SET_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R3
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R3
          sbrc 	 r25, 	 5	 ; (OP_SBRC, r25, bit, b) ; BIT5
          rjmp 	 l_0003cd 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_COIL
    ; INT_COPY_BIT_TO_BIT YMemoria_arriba:=$rung_top
l_0003cd: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x2B	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 7	 ; (OP_BLD, r25, bitDest, d) ; BIT7
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; YMemoria_arriba
    ; ] finish series
    ; 
    ; ======= START RUNG 15 =======
    ; INT_AllocKnownAddr Rung15
    ; INT_SET_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          sbr 	 r25, 	 0x1	 ; (OP_SBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; start series [
    ; ELEM_CONTACTS
    ; INT_IF_BIT_CLEAR R7
          ldi 	 r30, 	 0x4	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name) ; R7
          sbrc 	 r25, 	 5	 ; (OP_SBRC, r25, bit, b) ; BIT5
          rjmp 	 l_0003e5 	 ; (OP_RJMP, condFalse)
    ; INT_CLEAR_BIT $rung_top
          ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, reg, 0, name) ; $rung_top
          cbr 	 r25, 	 0x1	 ; (OP_CBR, reg, 1 << bit)
          st  	 Z, 	 r25	 ; (OP_ST_Z, reg)
    ; ELEM_COIL
    ; INT_COPY_BIT_TO_BIT YMemmoria_baja:=$rung_top
l_0003e5: ldi 	 r30, 	 0x0	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x1	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25, 0, name2) ; $rung_top
          bst 	 r25, 	 0	 ; (OP_BST, r25, bitSrc, s) ; BIT0
          ldi 	 r30, 	 0x2B	 ; (OP_LDI, ZL, (addr & 0xff), comment)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8))
          ld  	 r25, 	 Z	 ; (OP_LD_Z, r25)
          bld 	 r25, 	 6	 ; (OP_BLD, r25, bitDest, d) ; BIT6
          st  	 Z, 	 r25	 ; (OP_ST_Z, r25, 0, name1) ; YMemmoria_baja
    ; ] finish series
    ; INT_AllocKnownAddr Rung16
    ; Latest INT_OP here
    ; CompileFromIntermediate END
    ; GOTO next PLC cycle
          ldi 	 r30, 	 0x66	 ; (OP_LDI, ZL, addr & 0xff)
          ldi 	 r31, 	 0x0	 ; (OP_LDI, ZH, (addr >> 8) & 0xff)
          ijmp 	 		 ; (OP_IJMP, addr)
l_0003f1: rjmp 	 l_0003f1 	 ; (OP_RJMP, AvrProg.size())

;|  # | Name                                                    | Size      | Address      | Bit # |
;|Variables: 37
;| 19 | T1                                                	|   1 byte  | 0x0101       |
;| 22 | T2                                                	|   1 byte  | 0x0102       |
;| 24 | T3                                                	|   1 byte  | 0x0103       |
;| 27 | T4                                                	|   1 byte  | 0x0105       |
;| 29 | T5                                                	|   1 byte  | 0x0106       |
;| 36 | T6                                                	|   1 byte  | 0x0107       |

;|Internal Relays: 20
;|  0 | $rung_top                                         	|   1 bit   | 0x0100       | 0     |
;|  1 | R1                                                	|   1 bit   | 0x0100       | 1     |
;|  2 | $parThis_0                                        	|   1 bit   | 0x0100       | 2     |
;|  3 | R2                                                	|   1 bit   | 0x0100       | 3     |
;|  4 | $parThis_1                                        	|   1 bit   | 0x0100       | 4     |
;|  5 | R3                                                	|   1 bit   | 0x0100       | 5     |
;|  6 | $parThis_2                                        	|   1 bit   | 0x0100       | 6     |
;|  7 | R4                                                	|   1 bit   | 0x0100       | 7     |
;|  8 | $parThis_3                                        	|   1 bit   | 0x0104       | 0     |
;|  9 | R5                                                	|   1 bit   | 0x0104       | 1     |
;| 10 | $parThis_4                                        	|   1 bit   | 0x0104       | 2     |
;| 11 | R6                                                	|   1 bit   | 0x0104       | 3     |
;| 12 | $parThis_5                                        	|   1 bit   | 0x0104       | 4     |
;| 13 | R7                                                	|   1 bit   | 0x0104       | 5     |
;| 14 | $parThis_6                                        	|   1 bit   | 0x0104       | 6     |
;| 15 | R8                                                	|   1 bit   | 0x0104       | 7     |
;| 16 | $parOut_0                                         	|   1 bit   | 0x0108       | 0     |
;| 17 | $parThis_7                                        	|   1 bit   | 0x0108       | 1     |
;| 18 | $parOut_1                                         	|   1 bit   | 0x0108       | 2     |
;| 19 | $parThis_8                                        	|   1 bit   | 0x0108       | 3     |

